#!/usr/bin/php
<?php

declare(strict_types=1);

require __DIR__ . '/src/App/App.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new App\Command\CrudGeneratorCommand($app));

$application->run();
