#!/usr/bin/php
<?php

declare(strict_types=1);

use Symfony\Component\Console\Application;

require __DIR__ . '/src/App/App.php';

$application = new Application();
$application->add(new App\Command\CrudGeneratorCommand($app));
$application->run();
