#!/usr/bin/php
<?php declare(strict_types=1);

require __DIR__ . '/App.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new App\Commands\Utils\GenerateCrudEntityCommand($app));

$application->run();
